language: node_js
node_js:
  - "0.10"

notifications:
  email:
    recipients:
      - martinmicunda@hotmail.com
    on_success: never
    on_failure: always

env:
  global:
    - secure: 'O8EunBCVEttAgCbs9eRKDfANt5WY1zdoSnx2nCrh6SQz3up1vIIwh4QXz6H/JwnlmsN6/xIgZnO9DJWqDboCWpfFpze6kJ8KuViE0MxSAcnM5/1iXxXQoXZPo/QQ5vt0j4o/m6L1bhy7PQIwbSJH08OhXcVQtH/cHKO2m8zQBi8='

# starts xvfb on display port :99.0 (virtual Firefox)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# install dependencies necessary to run this build
install:
#  - npm install -g gulp@3.6.x karma@0.12.x protractor@0.21.x
#  - npm install --quiet

# configure Travis CI
before_script:
#  - node server/src/server.js &
#  - sleep 3 # give server some time to start
  - gulp build

# run unit and e2e tests
script:
  - gulp test-unit

# publish build to gh-pages branch
after_script:
  - git config --global user.email "martinmicunda@hotmail.com"
  - git config --global user.name "Travis-CI"
  - gulp gh-pages