language: node_js
node_js:
  - "0.10"

notifications:
  email:
    recipients:
      - martinmicunda@hotmail.com
    on_success: never
    on_failure: always

# starts xvfb on display port :99.0 (virtual Firefox)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# install dependencies necessary to run this build
install:
  - npm install -g gulp@3.5.x karma@0.12.x protractor@0.21.x
  - npm install --quiet

# configure Travis CI
before_script:
  - cd /server/src/
  - node server.js &
  - sleep 3 # give server some time to start

script:
  - gulp test-unit