language: node_js
node_js:
  - "0.10"

notifications:
  email:
    recipients:
      - martinmicunda@hotmail.com
    on_success: never
    on_failure: always

env:
  global:
    # travis-encrypt -r martinmicunda/employee-scheduling -k GH_TOKEN -v <https://help.github.com/articles/creating-an-access-token-for-command-line-use> --add env.globa
    - secure: O8EunBCVEttAgCbs9eRKDfANt5WY1zdoSnx2nCrh6SQz3up1vIIwh4QXz6H/JwnlmsN6/xIgZnO9DJWqDboCWpfFpze6kJ8KuViE0MxSAcnM5/1iXxXQoXZPo/QQ5vt0j4o/m6L1bhy7PQIwbSJH08OhXcVQtH/cHKO2m8zQBi8=
    # COVERALLS_REPO_TOKEN
    - secure: YDGbgsTSvN9evJIRhX22Y+P56VYK50bT1tnQrkMxLRANyyQc6UF/e5iKWm+Yy4/0OWq12o+2tTvBc/MgdwSE+t28E+VmdF/JcQDY2pHb8szQ6PjS1PCkeq3IbYvdsYTSAWOBa9coqXECwkwEdtI6tuGQpXL/MOnq7ZncOetdpF4=
    # HEROKU_API_KEY
    - secure: eNQJbfy4sB1tCZXbkmHeb9+APA2jYL3Zrp/q9h2JvhAvtsH804gK5p+Dg5y3AA6wKnpwqm03/i4BVCUn6UK9Ono2hjxZfksQDtknNdR8UMaRvA3Iymd1vCpLJnuVtocU2QfFiXYEVIuKdHkIm4ut53Is2URHwOJrtysaLTkt3Yo=

branches:
  only:
    - master
    - deploy

# starts xvfb on display port :99.0 (virtual display for Firefox)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# install dependencies necessary to run this build
install:
  - npm install --quiet

#before_script:
#  - sudo add-apt-repository ppa:git-core/ppa -y
#  - sudo apt-get update
#  - sudo apt-get install git -y

script:
  - bash -ex ./ci_build.sh

#after_success:
#  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
#  - git remote add heroku git@heroku.com:employee-scheduling.git
#  - echo "Host heroku.com" >> ~/.ssh/config
#  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
#  - echo "   CheckHostIP no" >> ~/.ssh/config
#  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
#  - yes | heroku keys:add
#  - yes | git subtree push --prefix build heroku master

deploy:
  provider: heroku
  api_key:
    secure: i5m+ZKuyoEf/bXwqTEWnZXM5Ge0mAqreIfDr0pvicSpkVYcWkoe2ynQ5ZmlB5HnEOUW9NIuQNft3j29wt0wIw+axVDTK9XTB0sWP9vvCXYuTstyZ4GhhzlEGNX1fJt5ZyRuwFrIWP/vraLE+tNBLXuB0s8h02zQ5V2kXTezJMJU=
  app:
    deploy: employee-scheduling
