---
galaxy_info:
  author: Martin Micunda
  description: Install the latest stable version of Nginx, configure sites-available.
  license: MIT
  min_ansible_version: 1.7
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
  - networking
  - web

dependencies: []
