---
- name: Install ppa key
  apt_key: >
    id=7F0CEB10
    url=http://docs.mongodb.org/10gen-gpg-key.asc
    state=present
  sudo: yes
  tags: mongodb

- name: Add repo to the sources list
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen
  sudo: yes

- name: Install mongo server v {{ mongodb_version }}
  sudo: yes
  apt: >
    pkg="mongodb-org={{mongodb_version}}"
    state=present
    update-cache=yes
  tags: mongodb

- name: Create mongo dirs
  file: >
    path="{{ item }}" state=directory
    owner="{{ mongodb_user }}"
    group="{{ mongodb_group }}"
  with_items:
    - "{{ mongodb_path }}"
  tags: mongodb

#- name: Stop mongo service
#  service: name=mongodb state=stopped
#  tags: mongodb

#- name: Move mongodb to {{ mongodb_path }}
#  command: mv /var/lib/mongodb  {{ mongo_data_dir}}/.  creates={{ mongo_data_dir }}/mongodb

## Configure user
#- name: Setup group
#  sudo: yes
#  user: name={{ mongodb_group }}
#- name: Setup user
#  sudo: yes
#  user: name={{ mongodb_user }} group={{ mongodb_group }} home="{{ mongodb_path }}" shell="/bin/false" comment="MongoDB Server"

- name: Copy the mongod conf file
  sudo: yes
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify: restart mongodb
  tags: mongodb

#- name: Start mongo service
#  service: name=mongodb state=started
#  tags: mongodb
