---
# Apiservers deployment playbook.

- name: deploy node and configure api servers
  hosts: apiservers
  sudo: yes
  roles:
    - role: martinmicunda.common
    - role: martinmicunda.nodejs
    - role: martinmicunda.gulp
