---
- name: Create VM box for development
  hosts: all
  sudo: yes
  roles:
    - angstwad.docker_ubuntu
    - franklinkim.docker-compose
    - martinmicunda.common
    - martinmicunda.iojs
    - laggyluke.direnv
  tasks:
    - name: add user vagrant to the docker group to avoid type sudo for each docker command
      user: name=vagrant
            groups=docker
            append=yes
