---
- name: Install io.js, nsqd and consul on given set of nodes
  hosts: iojs-servers
  sudo: yes
  roles:
    - role: martinmicunda.common
    - role: martinmicunda.iojs
#    - role: laggyluke.direnv
#    - { role: nsq, nsq_nsqd_server: true }
    - role: savagegus.consul
#  vars:
#    consul_datacenter: "employee-scheduling"
#    consul_join_at_start: true
#    consul_servers: ['192.168.33.16']
#    consul_node_name: "{{ ansible_hostname }}"
#    consul_client_address: "0.0.0.0"
#    consul_advertise_address: "{{ ansible_eth1['ipv4']['address'] }}"
  tasks:
    - name: add iojs and nsqd consul services
      template: src=templates/api.json.j2 dest=/etc/consul.d/api.json
      notify:
      - restart consul

