---
- name: Install nsqadmin and consul client agent on given set of nodes
  hosts: nsqadmin-servers
  sudo: yes
  roles:
    - role: savagegus.consul
    - { role: nsq, nsq_nsqadmin_server: true }
  tasks:
    - debug: msg="{{ consul_node_name }}"
    - debug: msg="{{ inventory_hostname }}"
    - debug: msg="{{ consul_advertise_address }}"
    - name: add nsqadmin consul service
      template: src=templates/nsq_nsqadmin.json.j2 dest=/etc/consul.d/nsq_nsqadmin.json
      notify:
      - restart consul
