---
# Webservers deployment playbook.

- name: deploy nginx and configure web servers
  hosts: uiservers
  sudo: yes
  roles:
#    - role: martinmicunda.common
    - { role: nginx, sudo: yes, tags: nginx }
#    - role: martinmicunda.nodejs
#    - role: martinmicunda.bower
#    - role: martinmicunda.gulp
