#api:
#    build: ./node
#    links:
#        - redis
#    ports:
#        - "8080"
#api:
#    build: .
#    links:
#        - db
#    ports:
#        - "3030:3000"
#api:
#  image: iojs:2.2.1
#  links:
#    - db
#  ports:
#    - "3030:3000"
db:
  image: couchbase/server:community-3.0.1
  ports:
    - "8091:8091"
    - "11210:11210" # this should not be required once I will get link containers work together

#¡¡¡ https://blog.codeship.com/orchestrate-containers-for-development-with-docker-compose/
# https://github.com/CodeshipExamples/docker-compose
# https://blog.docker.com/2015/04/easily-configure-apps-for-multiple-environments-with-compose-1-2-and-much-more/
# http://arrowconcept.com/setting-up-nodejs-micro-services-with-docker-compose-nginx-and-rethinkdb/
